variant: default
manifest:
    # Name of the web application (default to the site title)
    name: Icaurs - Hexo Theme
    # The displayed name of the web application
    # when there is not enough space to display full name
    short_name: Icarus
    # The start URL of the web application
    start_url: https://ppoffice.github.io/
    # The default theme color for the application
    theme_color: "#3273dc"
    # A placeholder background color for the application page to display
    # before its stylesheet is loaded
    background_color: "#3273dc"